# Generated by Django 5.1.5 on 2025-03-04 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookStatuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NewBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('publishyear', models.PositiveSmallIntegerField()),
                ('language', models.CharField(max_length=200)),
                ('pagenumber', models.PositiveIntegerField()),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('type', models.CharField(max_length=200)),
                ('statues', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recording.bookstatuses')),
            ],
        ),
        migrations.CreateModel(
            name='EditExcerpt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='书摘标题')),
                ('content', models.TextField(null=True, verbose_name='书摘内容')),
                ('feeling', models.TextField(null=True, verbose_name='书摘心得')),
                ('page_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='页码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='excerpts', to='recording.newbook')),
            ],
        ),
    ]
