# Generated by Django 5.1.5 on 2025-03-05 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recording', '0002_newbook_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newbook',
            name='statues',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='recording.bookstatuses'),
        ),
    ]
