# Generated by Django 3.2.15 on 2025-03-12 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recording', '0004_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newbook',
            name='type',
        ),
        migrations.AddField(
            model_name='newbook',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent__isnull': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='recording.category'),
        ),
        migrations.AddField(
            model_name='newbook',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_books', to='recording.category'),
        ),
    ]
